### ISSUE TITLE
Middleware Collection Validation

### ISSUE THREAD

**Issue by dolfelt** [sparkphp/spark#48]
It appears that the middleware validation isn't working correctly [here](https://github.com/sparkphp/spark/blob/master/src/Middleware/Collection.php#L26).

@elazar @shadowhand @ameech

**Comment by elazar** [comment]
@dolfelt How do you figure? There's a [test case](https://github.com/sparkphp/spark/blob/4c31776e9212b9f33d4f928242e39e96e5ee3f92/tests/Middleware/CollectionTest.php#L13-L22) that should cover that.

**Comment by elazar** [comment]
Never mind, I see what you mean now: [this is expecting instances](https://github.com/sparkphp/spark/blob/4c31776e9212b9f33d4f928242e39e96e5ee3f92/src/Middleware/Collection.php#L26), [this is assuming class names](https://github.com/sparkphp/spark/blob/4c31776e9212b9f33d4f928242e39e96e5ee3f92/src/Middleware/DefaultCollection.php#L17-L22). The issue is that middlewares presently don't have access to the injector, where configurations do, so they're able to use class names. Not sure how we should go about fixing this.

**Comment by shadowhand** [comment]
Since the collection doesn't need to be resolved [until Relay gets built](https://github.com/sparkphp/spark/blob/5f07a1a896d1e1ee8319fb00060f68b8762d7863/src/Configuration/RelayConfiguration.php#L26) and we have the resolver available in this context, couldn't we use class strings until we reach this point, and then pass the middleware through the resolver to create instances?
